version: '3.4'

services:
  app:
    image: rtve
    container_name: app_rtve
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    links:
      - db_postgres
      - db_redis

    command: bash -c "poetry install && poetry run python manage.py makemigrations accounts --noinput && poetry run python manage.py makemigrations --noinput && poetry run python manage.py migrate --noinput && poetry run python manage.py runserver 0.0.0.0:8000 --insecure"


  db_redis:
    image: redis:latest
    container_name: db_redis
    ports:
      - "6379:6379"

  db_postgres:
    image: postgres:13
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment :
      POSTGRES_DB: db_rtve
      POSTGRES_USER: user_rtve
      POSTGRES_PASSWORD: password_rtve

    volumes:
      - pg-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm

volumes:
  pg-data:
